local g = Global
local legion = Legion

g.data = {
    {
        name = 'Zones',
        entries = {
            {
                name = 'Vanilla',
                entries = {
                    {
                        name = 'Kalimdor',
                        entries = {
                            { name = 'Ashenvale' },
                            { name = 'Azshara' },
                            { name = 'Darkshore' },
                            { name = 'Darnassus' },
                            { name = 'Desolace' },
                            { name = 'Durotar' },
                            { name = 'Dustwallow Marsh' },
                            { name = 'Felwood' },
                            { name = 'Feralas' },
                            { name = 'Moonglade' },
                            { name = 'Mulgore' },
                            { name = 'Northern Barrens' },
                            { name = 'Orgrimmar' },
                            { name = 'Silithus' },
                            { name = 'Southern Barrens' },
                            { name = 'Stonetalon Mountains' },
                            { name = 'Teldrassil' },
                            { name = 'Thousand Needles' },
                            { name = 'Thunder Bluff' },
                            { name = "Un'goro Crater" },
                            { name = 'Winterspring' },
                        }
                    },
                    {
                        name = 'Eastern Kingdoms',
                        entries = {
                            { name = 'Arathi Highlands' },
                            { name = 'Badlands' },
                            { name = 'Blasted Lands' },
                            { name = 'Burning Steppes' },
                            { name = 'Deadwind Pass' },
                            { name = 'Dun Morogh' },
                            { name = 'Duskwood' },
                            { name = 'Eastern Plaguelands' },
                            { name = 'Elwynn Forest' },
                            { name = 'Hillsbrad Foothills' },
                            { name = 'The Hinterlands' },
                            { name = 'Ironforge' },
                            { name = 'Loch Modan' },
                            { name = 'Redridge Mountains' },
                            { name = 'Searing Gorge' },
                            { name = 'Silverpine Forest' },
                            { name = 'Stormwind City' },
                            { name = 'Stranglethorn Vale' },
                            { name = 'Swamp of Sorrows' },
                            { name = 'Tirisfal Glades' },
                            { name = 'Undercity' },
                            { name = 'Western Plaguelands' },
                            { name = 'Westfall' },
                            { name = 'Wetlands' },
                        }
                    },
                }
            },
            {
                name = 'The Burning Crusade',
                entries = {
                    { name = 'Azuremyst Isle' },
                    { name = "Blade's Edge Mountains" },
                    { name = 'Bloodmyst Isle' },
                    { name = 'Eversong Woods' },
                    { name = 'The Exodar' },
                    { name = 'Ghostlands' },
                    { name = 'Hellfire Peninsula' },
                    { name = "Isle of Quel'Danas" },
                    { name = 'Nagrand' },
                    { name = 'Netherstorm' },
                    { name = 'Shadowmoon Valley' },
                    { name = 'Shattrath City' },
                    { name = 'Silvermoon City' },
                    { name = 'Terokkar Forest' },
                    { name = 'Zangarmarsh' },
                }
            },
            {
                name = 'Wrath of the Lich King',
                entries = {
                    { name = 'Borean Tundra' },
                    { name = 'Crystalsong Forest' },
                    { name = 'Dalaran' },
                    { name = 'Dragonblight' },
                    {
                        name = 'Grizzly Hills',
                        songs = {
                            'ZoneMusic/GrizzlyHills/GH_Intro2Uni01'
                        }
                    },
                    { name = 'Howling Fjord' },
                    { name = 'Icecrown' },
                    { name = 'Sholazar Basin' },
                    { name = 'Storm Peaks' },
                    { name = 'Wintergrasp' },
                    { name = "Zul'Drak" },
                }
            },
            {
                name = 'Cataclysm',
                entries = {
                    { name = 'Deepholm' },
                    { name = 'Kezan' },
                    { name = 'The Lost Isles' },
                    { name = 'Mount Hyjal' },
                    { name = 'Ruins of Gilneas' },
                    { name = 'Tol Barad' },
                    { name = 'Twilight Highlands' },
                    { name = 'Uldum' },
                    {
                        name = "Vashj'ir",
                        entries = {
                            { name = 'Abyssal Depths' },
                            { name = "Kelp'thar Forest" },
                            { name = 'Shimmering Expanse' },
                        }
                    },
                }
            },
            {
                name = 'Mists of Pandaria',
                entries = {
                    { name = 'Dread Wastes' },
                    { name = 'Isle of Giants' },
                    { name = 'Isle of Thunder' },
                    { name = 'The Jade Forest' },
                    { name = 'Krasarang Wilds' },
                    { name = 'Kun-Lai Summit' },
                    { name = 'Timeless Isle' },
                    { name = 'Townlong Steppes' },
                    { name = 'Vale of Eternal Blossoms' },
                    { name = 'Valley of the Four Winds' },
                }
            },
            {
                name = 'Warlords of Draenor',
                entries = {
                    { name = 'Ashran' },
                    { name = 'Frostfire Ridge' },
                    { name = 'Gorgrond' },
                    { name = 'Nagrand' },
                    { name = 'Shadowmoon Valley' },
                    { name = 'Spires of Arak' },
                    { name = 'Talador' },
                    { name = 'Tanaan Jungle' },
                }
            },
            legion
        }
    },
    {
        name = 'Login Screens',
        songs = {
            'GlueScreenMusic/wow_main_theme',
            'GlueScreenMusic/bc_main_theme',
            'GlueScreenMusic/wotlk_main_title',
            'cataclysm/MUS_Shattering_UU01',
            'Pandaria/MUS_50_HeartofPandaria_01',
            'Draenor/MUS_60_ASiegeofWorlds_MainTitle',
            'legion/MUS_70_Kingdomswillburn_MainTitle',
        }
    },
    {
        name = 'Blizzard\'s Sorting',
        entries = {
            {
                name = 'cataclysm',
                songs = {
                    'cataclysm/mus_41_faeriedragon_ue01',
                    'cataclysm/mus_41_za_altarbloodgod_uu01',
                    'cataclysm/mus_41_za_altarbloodgod_uu02',
                    'cataclysm/mus_41_za_altarbloodgod_uu03',
                    'cataclysm/mus_41_za_bethekk_uu01',
                    'cataclysm/mus_41_za_bethekk_uu02',
                    'cataclysm/mus_41_za_cacheofmadness_uu01',
                    'cataclysm/mus_41_za_cacheofmadness_uu02',
                    'cataclysm/mus_41_za_devilsterrace_uu01',
                    'cataclysm/mus_41_za_devilsterrace_uu02',
                    'cataclysm/mus_41_za_mandokir_uu01',
                    'cataclysm/mus_41_za_mandokir_uu02',
                    'cataclysm/mus_41_za_templebethek_uu01',
                    'cataclysm/mus_41_za_templebethek_uu02',
                    'cataclysm/mus_41_za_terracedevils_uu01',
                    'cataclysm/mus_41_za_terracedevils_uu02',
                    'cataclysm/mus_41_za_thecoil_uu01',
                    'cataclysm/mus_41_za_thecoil_uu02',
                    'cataclysm/mus_42_druidsoftheflamea_hero_uu01',
                    'cataclysm/mus_42_druidsoftheflamea_uu01',
                    'cataclysm/mus_42_druidsoftheflamea_uu02',
                    'cataclysm/mus_42_druidsoftheflamea_uu03',
                    'cataclysm/mus_42_druidsoftheflameb_hero_uu01',
                    'cataclysm/mus_42_druidsoftheflameb_uu01',
                    'cataclysm/mus_42_druidsoftheflameb_uu02',
                    'cataclysm/mus_42_druidsoftheflameb_uu03',
                    'cataclysm/mus_42_elementalbondsa_uu01',
                    'cataclysm/mus_42_elementalbondsa_uu02',
                    'cataclysm/mus_42_elementalbondsa_uu03',
                    'cataclysm/mus_42_elementalbondsb_uu01',
                    'cataclysm/mus_42_elementalbondsb_uu02',
                    'cataclysm/mus_42_elemental_aira_uu01',
                    'cataclysm/mus_42_elemental_aira_uu02',
                    'cataclysm/mus_42_elemental_airb_uu01',
                    'cataclysm/mus_42_elemental_airb_uu02',
                    'cataclysm/mus_42_elemental_airc_uu01',
                    'cataclysm/mus_42_elemental_aird_uu01',
                    'cataclysm/mus_42_elemental_aird_uu02',
                    'cataclysm/mus_42_elemental_eartha_uu01',
                    'cataclysm/mus_42_elemental_eartha_uu02',
                    'cataclysm/mus_42_elemental_eartha_uu03',
                    'cataclysm/mus_42_elemental_eartha_uu04',
                    'cataclysm/mus_42_elemental_watera_ud01',
                    'cataclysm/mus_42_elemental_watera_un01',
                    'cataclysm/mus_42_elemental_waterb_ud01',
                    'cataclysm/mus_42_elemental_waterb_un01',
                    'cataclysm/mus_42_elemental_waterc_ud01',
                    'cataclysm/mus_42_elemental_waterc_un01',
                    'cataclysm/mus_42_elemental_water_ambient_uu01',
                    'cataclysm/mus_42_firelandsa_hero_uu01',
                    'cataclysm/mus_42_firelandsa_uu01',
                    'cataclysm/mus_42_firelandsa_uu02',
                    'cataclysm/mus_42_firelandsa_uu03',
                    'cataclysm/mus_42_firelandsb_hero_uu01',
                    'cataclysm/mus_42_firelandsb_uu01',
                    'cataclysm/mus_42_firelandsb_uu02',
                    'cataclysm/mus_42_firelandsb_uu03',
                    'cataclysm/mus_42_firelandsb_uu04',
                    'cataclysm/mus_42_thrallaggraa_ed01',
                    'cataclysm/mus_42_thrallaggraa_en01',
                    'cataclysm/mus_42_thrallaggrab_ed01',
                    'cataclysm/mus_42_thrallaggrab_en01',
                    'cataclysm/mus_42_thrallaggrac_eu01',
                    'cataclysm/mus_42_thrallaggrac_eu02',
                    'cataclysm/mus_43_corrupteddragonblight_uu01',
                    'cataclysm/mus_43_corrupteddragonblight_uu02',
                    'cataclysm/mus_43_corrupteddragonblight_uu03',
                    'cataclysm/mus_43_deathwingcorruption_uu01',
                    'cataclysm/mus_43_deathwingcorruption_uu02',
                    'cataclysm/mus_43_deathwingcorruption_uu03',
                    'cataclysm/mus_43_deathwingcorruption_uu04',
                    'cataclysm/mus_43_deathwingcorruption_uu05',
                    'cataclysm/mus_43_deathwingcorruption_uu06',
                    'cataclysm/mus_43_deathwingcorruption_uu07',
                    'cataclysm/mus_43_deathwingoutro_uu01',
                    'cataclysm/mus_43_deathwingsfall_hero_uu01',
                    'cataclysm/mus_43_deathwingsfall_uu01',
                    'cataclysm/mus_43_deathwingsfall_uu02',
                    'cataclysm/mus_43_dragonsoula_hero_uu01',
                    'cataclysm/mus_43_dragonsoula_moment_01',
                    'cataclysm/mus_43_dragonsoula_moment_02',
                    'cataclysm/mus_43_dragonsoula_moment_03',
                    'cataclysm/mus_43_dragonsoula_moment_04',
                    'cataclysm/mus_43_dragonsoulb_uu01',
                    'cataclysm/mus_43_dragonsoulb_uu02',
                    'cataclysm/mus_43_dragonsoulb_uu03',
                    'cataclysm/mus_43_fangsofthefathera_hero_uu01',
                    'cataclysm/mus_43_fangsofthefathera_uu01',
                    'cataclysm/mus_43_fangsofthefathera_uu02',
                    'cataclysm/mus_43_fangsofthefathera_uu03',
                    'cataclysm/mus_43_fangsofthefatherb_uu01',
                    'cataclysm/mus_43_fangsofthefatherb_uu02',
                    'cataclysm/mus_43_fangsofthefatherb_uu03',
                    'cataclysm/mus_43_fangsofthefatherc_hero_uu01',
                    'cataclysm/mus_43_fangsofthefatherc_uu02',
                    'cataclysm/mus_43_fangsofthefatherc_uu03',
                    'cataclysm/mus_43_fangsofthefatherc_uu04',
                    'cataclysm/mus_43_gunships_hero_uu01',
                    'cataclysm/mus_43_gunships_stinger_01',
                    'cataclysm/mus_43_gunships_stinger_02',
                    'cataclysm/mus_43_gunships_stinger_03',
                    'cataclysm/mus_43_gunships_stinger_04',
                    'cataclysm/mus_43_gunships_uu01',
                    'cataclysm/mus_43_gunships_uu02',
                    'cataclysm/mus_43_gunships_uu03',
                    'cataclysm/mus_43_gunships_uu04',
                    'cataclysm/mus_43_nightwalk_uu01',
                    'cataclysm/mus_43_nightwalk_uu02',
                    'cataclysm/mus_43_nightwalk_uu03',
                    'cataclysm/mus_43_nightwalk_uu04',
                    'cataclysm/mus_43_thrallearthwarder_uu01',
                    'cataclysm/mus_43_thrallearthwarder_uu02',
                    'cataclysm/mus_43_thrallearthwarder_uu03',
                    'cataclysm/mus_43_thrallearthwarder_uu04',
                    'cataclysm/mus_43_twilightshammer_uu01',
                    'cataclysm/mus_43_twilightshammer_uu02',
                    'cataclysm/mus_43_warships_hero_01',
                    'cataclysm/mus_43_warships_uu01',
                    'cataclysm/mus_43_warships_uu02',
                    'cataclysm/mus_43_wellofeternity_hero_uu01',
                    'cataclysm/mus_43_wellofeternity_uu01',
                    'cataclysm/mus_43_wellofeternity_uu02',
                    'cataclysm/mus_43_wellofeternity_uu03',
                    'cataclysm/mus_43_wellofeternity_uu04',
                    'cataclysm/mus_43_wellofeternity_uu05',
                    'cataclysm/mus_43_wellofeternity_uu06',
                    'cataclysm/mus_43_zinazshari_hero_uu01',
                    'cataclysm/mus_43_zinazshari_uu01',
                    'cataclysm/mus_43_zinazshari_uu02',
                    'cataclysm/mus_43_zinazshari_uu03',
                    'cataclysm/mus_43_zinazshari_uu04',
                    'cataclysm/mus_43_zinazshari_uu05',
                    'cataclysm/mus_43_zinazshari_uu06',
                    'cataclysm/mus_adventurea_hero_uu01',
                    'cataclysm/mus_adventurea_moment_uu01',
                    'cataclysm/mus_adventurea_moment_uu02',
                    'cataclysm/mus_adventurea_moment_uu03',
                    'cataclysm/mus_adventurea_moment_uu04',
                    'cataclysm/mus_adventurea_uu01',
                    'cataclysm/mus_adventurea_uu03',
                    'cataclysm/mus_adventurea_uu04',
                    'cataclysm/mus_adventurea_uu05',
                    'cataclysm/mus_adventurea_uu06',
                    'cataclysm/mus_aftermath_uu01',
                    'cataclysm/mus_aftermath_uu02',
                    'cataclysm/mus_aftermath_uu03',
                    'cataclysm/mus_aftermath_uu04',
                    'cataclysm/mus_alliancehero_uu01',
                    'cataclysm/mus_arathihighlandsa_gd01',
                    'cataclysm/mus_arathihighlandsa_gn01',
                    'cataclysm/mus_arathihighlandsa_gn02',
                    'cataclysm/mus_arathihighlandsb_gd01',
                    'cataclysm/mus_arathihighlandsb_gn01',
                    'cataclysm/mus_arathihighlandsb_gn02',
                    'cataclysm/mus_arathihighlandsc_gd01',
                    'cataclysm/mus_arathihighlandsc_gn01',
                    'cataclysm/mus_arathihighlandsc_gn02',
                    'cataclysm/mus_azshara_gd01',
                    'cataclysm/mus_azshara_gn01',
                    'cataclysm/mus_barrowdens_gu01',
                    'cataclysm/mus_barrowdens_gu02',
                    'cataclysm/mus_barrowdens_gu03',
                    'cataclysm/mus_barrowdens_gu04',
                    'cataclysm/mus_barrowdens_gu05',
                    'cataclysm/mus_burningsteppes_gu01',
                    'cataclysm/mus_burningsteppes_gu02',
                    'cataclysm/mus_burningsteppes_gu03',
                    'cataclysm/mus_burningsteppes_gu04',
                    'cataclysm/mus_cataclysm_ud07',
                    'cataclysm/mus_cataclysm_un08',
                    'cataclysm/mus_cataclysm_un09',
                    'cataclysm/mus_cataclysm_uu01',
                    'cataclysm/mus_cataclysm_uu02',
                    'cataclysm/mus_cataclysm_uu03',
                    'cataclysm/mus_cataclysm_uu04',
                    'cataclysm/mus_cataclysm_uu05',
                    'cataclysm/mus_cataclysm_uu06',
                    'cataclysm/mus_chogall_e01',
                    'cataclysm/mus_chogall_e02',
                    'cataclysm/mus_chogall_e03',
                    'cataclysm/mus_chogall_e04',
                    'cataclysm/mus_coldmountain_gu01',
                    'cataclysm/mus_coldmountain_gu02',
                    'cataclysm/mus_coldmountain_gu03',
                    'cataclysm/mus_coldmountain_gu04',
                    'cataclysm/mus_coldmountain_gu05',
                    'cataclysm/mus_coldmountain_gu06',
                    'cataclysm/mus_coldmountain_gu07',
                    'cataclysm/mus_coldmountain_gu08',
                    'cataclysm/mus_crypt_uu01',
                    'cataclysm/mus_cursed_uu01',
                    'cataclysm/mus_cursed_uu02',
                    'cataclysm/mus_cursed_uu03',
                    'cataclysm/mus_cursed_uu04',
                    'cataclysm/mus_cursed_uu05',
                    'cataclysm/mus_cursed_uu06',
                    'cataclysm/mus_cursed_uu07',
                    'cataclysm/mus_cursed_uu08',
                    'cataclysm/mus_cursed_uu09',
                    'cataclysm/mus_cursed_uu10',
                    'cataclysm/mus_cursed_uu11',
                    'cataclysm/mus_cursed_uu12',
                    'cataclysm/mus_darkevent_e01',
                    'cataclysm/mus_darkironforge_gu01',
                    'cataclysm/mus_darkironforge_gu02',
                    'cataclysm/mus_darkironforge_gu03',
                    'cataclysm/mus_darkironforge_gu04',
                    'cataclysm/mus_darkironforge_gu05',
                    'cataclysm/mus_darkironforge_gu06',
                    'cataclysm/mus_darkironforge_gu07',
                    'cataclysm/mus_darkwhispergorge_gu01',
                    'cataclysm/mus_darkwhispergorge_gu02',
                    'cataclysm/mus_darnassus_gi01',
                    'cataclysm/mus_darnassus_gi02',
                    'cataclysm/mus_deepholmevent_e01',
                    'cataclysm/mus_deepholmevent_e02',
                    'cataclysm/mus_deepholm_gu01',
                    'cataclysm/mus_deepholm_gu02',
                    'cataclysm/mus_durotara_gu01',
                    'cataclysm/mus_durotara_gu02',
                    'cataclysm/mus_durotara_gu03',
                    'cataclysm/mus_durotarb_gu01',
                    'cataclysm/mus_durotarb_gu02',
                    'cataclysm/mus_durotarb_gu03',
                    'cataclysm/mus_durotarb_gu04',
                    'cataclysm/mus_durotarc_gu01',
                    'cataclysm/mus_durotarc_gu02',
                    'cataclysm/mus_durotarc_gu03',
                    'cataclysm/mus_durotarc_gu04',
                    'cataclysm/mus_durotard_gu01',
                    'cataclysm/mus_durotard_gu02',
                    'cataclysm/mus_elemental_uu01',
                    'cataclysm/mus_elemental_uu02',
                    'cataclysm/mus_elemental_uu03',
                    'cataclysm/mus_elemental_uu04',
                    'cataclysm/mus_elemental_uu05',
                    'cataclysm/mus_elemental_uu06',
                    'cataclysm/mus_elemental_uu07',
                    'cataclysm/mus_eyeofthevortex_gu01',
                    'cataclysm/mus_eyeofthevortex_gu02',
                    'cataclysm/mus_eyeofthevortex_gu03',
                    'cataclysm/mus_feralas_gu01',
                    'cataclysm/mus_feralas_gu02',
                    'cataclysm/mus_feralas_gu03',
                    'cataclysm/mus_feralas_gu04',
                    'cataclysm/mus_feralas_gu05',
                    'cataclysm/mus_feralas_gu06',
                    'cataclysm/mus_feralas_gu07',
                    'cataclysm/mus_feralas_gu08',
                    'cataclysm/mus_firelands_gu01',
                    'cataclysm/mus_fire_uu01',
                    'cataclysm/mus_fire_uu02',
                    'cataclysm/mus_floweraura_eu_01',
                    'cataclysm/mus_ghosts_uu01',
                    'cataclysm/mus_ghosts_uu02',
                    'cataclysm/mus_ghosts_uu03',
                    'cataclysm/mus_gilneasevent_e01',
                    'cataclysm/mus_gilneasevent_e02',
                    'cataclysm/mus_gilneasevent_e03',
                    'cataclysm/mus_gilneasevent_e04',
                    'cataclysm/mus_goblinhotrodradioloop_eu01',
                    'cataclysm/mus_goblin_uu01',
                    'cataclysm/mus_goblin_uu02',
                    'cataclysm/mus_goblin_uu03',
                    'cataclysm/mus_goblin_uu04',
                    'cataclysm/mus_goblin_uu05',
                    'cataclysm/mus_goblin_uu06',
                    'cataclysm/mus_goblin_uu07',
                    'cataclysm/mus_goblin_uu08',
                    'cataclysm/mus_goblin_uu09',
                    'cataclysm/mus_goblin_uu10',
                    'cataclysm/mus_goblin_uu11',
                    'cataclysm/mus_goblin_uu12',
                    'cataclysm/mus_goblin_uu13',
                    'cataclysm/mus_goblin_uu14',
                    'cataclysm/mus_goblin_uu15',
                    'cataclysm/mus_goblin_uu16',
                    'cataclysm/mus_goblin_uu17',
                    'cataclysm/mus_goblin_uu18',
                    'cataclysm/mus_goblin_uu19',
                    'cataclysm/mus_goblin_uu20',
                    'cataclysm/mus_goblin_uu21',
                    'cataclysm/mus_goblin_uu22',
                    'cataclysm/mus_goblin_uu23',
                    'cataclysm/mus_goblin_uu24',
                    'cataclysm/mus_goblin_uu25',
                    'cataclysm/mus_goblin_uu26',
                    'cataclysm/mus_goblin_uu27',
                    'cataclysm/mus_goblin_uu28',
                    'cataclysm/mus_goblin_uu29',
                    'cataclysm/mus_goblin_uu30',
                    'cataclysm/mus_goblin_uu31',
                    'cataclysm/mus_goblin_uu32',
                    'cataclysm/mus_goblin_uu33',
                    'cataclysm/mus_goblin_uu34',
                    'cataclysm/mus_goblin_uu35',
                    'cataclysm/mus_goblin_uu36',
                    'cataclysm/mus_goblin_uu37',
                    'cataclysm/mus_goblin_uu38',
                    'cataclysm/mus_goblin_uu39',
                    'cataclysm/mus_goblin_uu40',
                    'cataclysm/mus_goblin_uu41',
                    'cataclysm/mus_goblin_uu42',
                    'cataclysm/mus_goblin_uu43',
                    'cataclysm/mus_goblin_uu44',
                    'cataclysm/mus_goblin_uu45',
                    'cataclysm/mus_goblin_uu46',
                    'cataclysm/mus_goblin_uu47',
                    'cataclysm/mus_grimtotem_uu01',
                    'cataclysm/mus_grimtotem_uu02',
                    'cataclysm/mus_grimtotem_uu03',
                    'cataclysm/mus_grimtotem_uu04',
                    'cataclysm/mus_groveoftheancients_gu01',
                    'cataclysm/mus_groveoftheancients_gu02',
                    'cataclysm/mus_groveoftheancients_gu03',
                    'cataclysm/mus_groveoftheancients_gu04',
                    'cataclysm/mus_guardiansofhyjal_gu01',
                    'cataclysm/mus_guardiansofhyjal_gu02',
                    'cataclysm/mus_guardiansofhyjal_gu03',
                    'cataclysm/mus_guardiansofhyjal_gu04',
                    'cataclysm/mus_haunted_uu01',
                    'cataclysm/mus_haunted_uu02',
                    'cataclysm/mus_haunted_uu03',
                    'cataclysm/mus_hyjal_gu01',
                    'cataclysm/mus_hyjal_gu02',
                    'cataclysm/mus_hyjal_gu03',
                    'cataclysm/mus_hyjal_gu04',
                    'cataclysm/mus_landwillweep_uu01',
                    'cataclysm/mus_landwillweep_uu02',
                    'cataclysm/mus_lirescue_eu01',
                    'cataclysm/mus_lirescue_eu02',
                    'cataclysm/mus_lirescue_eu03',
                    'cataclysm/mus_lirescue_eu04',
                    'cataclysm/mus_lostcity_gu01',
                    'cataclysm/mus_lostcity_gu02',
                    'cataclysm/mus_lostcity_gu03',
                    'cataclysm/mus_lostcity_gu04',
                    'cataclysm/mus_lostcity_gu05',
                    'cataclysm/mus_marsh_uu01',
                    'cataclysm/mus_marsh_uu02',
                    'cataclysm/mus_marsh_uu03',
                    'cataclysm/mus_marsh_uu04',
                    'cataclysm/mus_marsh_uu05',
                    'cataclysm/mus_marsh_uu06',
                    'cataclysm/mus_marsh_uu07',
                    'cataclysm/mus_marsh_uu08',
                    'cataclysm/mus_moonglade_gu01',
                    'cataclysm/mus_moonglade_gu02',
                    'cataclysm/mus_moonglade_gu03',
                    'cataclysm/mus_moonglade_gu04',
                    'cataclysm/mus_moonglade_gu05',
                    'cataclysm/mus_moonglade_gu06',
                    'cataclysm/mus_moonglade_gu07',
                    'cataclysm/mus_mulgoreplains_gu01',
                    'cataclysm/mus_mulgoreplains_gu02',
                    'cataclysm/mus_mulgore_gu01',
                    'cataclysm/mus_mulgore_gu02',
                    'cataclysm/mus_mulgore_gu03',
                    'cataclysm/mus_mysterious_uu01',
                    'cataclysm/mus_nightelves_gu01',
                    'cataclysm/mus_nightelves_gu02',
                    'cataclysm/mus_nightelves_gu03',
                    'cataclysm/mus_nightelves_gu04',
                    'cataclysm/mus_nightelves_gu05',
                    'cataclysm/mus_nordrassil_gu01',
                    'cataclysm/mus_nordrassil_gu02',
                    'cataclysm/mus_nordrassil_gu03',
                    'cataclysm/mus_orgrimmarlegacy_gu01',
                    'cataclysm/mus_orgrimmar_gu01',
                    'cataclysm/mus_piratessurrender_uu01',
                    'cataclysm/mus_rift_uu01',
                    'cataclysm/mus_rift_uu02',
                    'cataclysm/mus_rift_uu03',
                    'cataclysm/mus_rift_uu04',
                    'cataclysm/mus_ruinsofauberdine_gu01',
                    'cataclysm/mus_ruinsofauberdine_gu02',
                    'cataclysm/mus_ruinsofauberdine_gu03',
                    'cataclysm/mus_ruinsofauberdine_gu04',
                    'cataclysm/mus_ruinsofauberdine_gu05',
                    'cataclysm/mus_scarred_uu01',
                    'cataclysm/mus_scarred_uu02',
                    'cataclysm/mus_scarred_uu03',
                    'cataclysm/mus_scarred_uu04',
                    'cataclysm/mus_shadowglen_gu01',
                    'cataclysm/mus_shadowglen_gu02',
                    'cataclysm/mus_shadowglen_gu03',
                    'cataclysm/mus_shadows_uu01',
                    'cataclysm/mus_shadows_uu02',
                    'cataclysm/mus_shadows_uu03',
                    'cataclysm/mus_shadows_uu04',
                    'cataclysm/mus_shadows_uu05',
                    'cataclysm/mus_shattering_uu01',
                    'cataclysm/mus_silithus_gu01',
                    'cataclysm/mus_silithus_gu02',
                    'cataclysm/mus_silithus_gu03',
                    'cataclysm/mus_silithus_gu04',
                    'cataclysm/mus_silithus_gu05',
                    'cataclysm/mus_silithus_gu06',
                    'cataclysm/mus_sirenquest_eu01',
                    'cataclysm/mus_skywall_gu01',
                    'cataclysm/mus_skywall_gu02',
                    'cataclysm/mus_skywall_gu03',
                    'cataclysm/mus_skywall_gu04',
                    'cataclysm/mus_skywall_gu05',
                    'cataclysm/mus_skywall_gu06',
                    'cataclysm/mus_skywall_gu07',
                    'cataclysm/mus_skywall_gu08',
                    'cataclysm/mus_skywall_gu09',
                    'cataclysm/mus_skywall_gu10',
                    'cataclysm/mus_southernbarrens_gu01',
                    'cataclysm/mus_southernbarrens_gu02',
                    'cataclysm/mus_southernbarrens_gu03',
                    'cataclysm/mus_southernbarrens_gu04',
                    'cataclysm/mus_southernbarrens_gu05',
                    'cataclysm/mus_southernbarrens_gu06',
                    'cataclysm/mus_stonetalon_gu01',
                    'cataclysm/mus_stonetalon_gu02',
                    'cataclysm/mus_stonetalon_gu03',
                    'cataclysm/mus_stonetalon_gu04',
                    'cataclysm/mus_stormwind_gu01',
                    'cataclysm/mus_stormwind_gu02',
                    'cataclysm/mus_stormwind_gu03',
                    'cataclysm/mus_stormwind_gu04',
                    'cataclysm/mus_stranglethornvale_gu01',
                    'cataclysm/mus_stranglethornvale_gu02',
                    'cataclysm/mus_stranglethornvale_gu03',
                    'cataclysm/mus_stranglethornvale_gu04',
                    'cataclysm/mus_stranglethorn_gu01',
                    'cataclysm/mus_stranglethorn_gu02',
                    'cataclysm/mus_stranglethorn_gu03',
                    'cataclysm/mus_stranglethorn_gu04',
                    'cataclysm/mus_tanaris_gu01',
                    'cataclysm/mus_tanaris_gu02',
                    'cataclysm/mus_tanaris_gu03',
                    'cataclysm/mus_tanaris_gu04',
                    'cataclysm/mus_tanaris_gu05',
                    'cataclysm/mus_tanaris_gu06',
                    'cataclysm/mus_tanaris_gu07',
                    'cataclysm/mus_tanaris_gu08',
                    'cataclysm/mus_tanaris_gu09',
                    'cataclysm/mus_tanaris_gu10',
                    'cataclysm/mus_tauren_uu01',
                    'cataclysm/mus_tauren_uu02',
                    'cataclysm/mus_thunderbluff_gu01',
                    'cataclysm/mus_thunderbluff_gu02',
                    'cataclysm/mus_thunderbluff_gu03',
                    'cataclysm/mus_treasure_uu01',
                    'cataclysm/mus_treasure_uu02',
                    'cataclysm/mus_treasure_uu03',
                    'cataclysm/mus_treasure_uu04',
                    'cataclysm/mus_treasure_uu05',
                    'cataclysm/mus_treasure_uu06',
                    'cataclysm/mus_twilighthighlands_gu01',
                    'cataclysm/mus_twilighthighlands_gu02',
                    'cataclysm/mus_twilighthighlands_gu03',
                    'cataclysm/mus_twilighthighlands_gu04',
                    'cataclysm/mus_twilighthighlands_gu05',
                    'cataclysm/mus_twilightshammer_uu01',
                    'cataclysm/mus_twilightshammer_uu02',
                    'cataclysm/mus_twilightshammer_uu03',
                    'cataclysm/mus_twilightvale_gu01',
                    'cataclysm/mus_twilightvale_gu02',
                    'cataclysm/mus_twilightvale_gu03',
                    'cataclysm/mus_twilightvale_gu04',
                    'cataclysm/mus_twilightvale_gu05',
                    'cataclysm/mus_ulduma_gu01',
                    'cataclysm/mus_ulduma_gu02',
                    'cataclysm/mus_ulduma_gu03',
                    'cataclysm/mus_ulduma_gu04',
                    'cataclysm/mus_ulduma_gu05',
                    'cataclysm/mus_uldumb_gu01',
                    'cataclysm/mus_uldumb_gu02',
                    'cataclysm/mus_uldumb_gu03',
                    'cataclysm/mus_uldumb_gu04',
                    'cataclysm/mus_uldumb_gu05',
                    'cataclysm/mus_uldumb_gu06',
                    'cataclysm/mus_uldumevent_e01',
                    'cataclysm/mus_undead_uu01',
                    'cataclysm/mus_undead_uu02',
                    'cataclysm/mus_undead_uu03',
                    'cataclysm/mus_undead_uu04',
                    'cataclysm/mus_undead_uu05',
                    'cataclysm/mus_vashjirnagathrone_gu01',
                    'cataclysm/mus_vashjirnagathrone_gu02',
                    'cataclysm/mus_vashjirnagathrone_gu03',
                    'cataclysm/mus_vashjirnagathrone_gu04',
                    'cataclysm/mus_vashjirnagathrone_gu05',
                    'cataclysm/mus_vashjirnagathrone_gu06',
                    'cataclysm/mus_vashjirnaga_gu01',
                    'cataclysm/mus_vashjirnaga_gu02',
                    'cataclysm/mus_vashjirnaga_gu03',
                    'cataclysm/mus_vashjirnaga_gu04',
                    'cataclysm/mus_vashjirnaga_gu05',
                    'cataclysm/mus_vashjirnaga_gu06',
                    'cataclysm/mus_vashjir_gu01',
                    'cataclysm/mus_vashjir_gu02',
                    'cataclysm/mus_vashjir_gu03',
                    'cataclysm/mus_vashjir_gu04',
                    'cataclysm/mus_vashjir_gu05',
                    'cataclysm/mus_vashjir_gu06',
                    'cataclysm/mus_vashjir_gu07',
                    'cataclysm/mus_vashjir_gu08',
                    'cataclysm/mus_vashjir_gu09',
                    'cataclysm/mus_warmarch_uu01',
                    'cataclysm/mus_westfall_gu01',
                    'cataclysm/mus_westfall_gu02',
                    'cataclysm/mus_westfall_gu03',
                    'cataclysm/mus_westfall_gu04',
                    'cataclysm/mus_westfall_gu05',
                    'cataclysm/mus_westplaguea_gd01',
                    'cataclysm/mus_westplaguea_gn01',
                    'cataclysm/mus_westplaguea_gn02',
                    'cataclysm/mus_westplagueb_gd01',
                    'cataclysm/mus_westplagueb_gn01',
                    'cataclysm/mus_westplagueb_gn02',
                    'cataclysm/mus_westplagueb_gn03',
                    'cataclysm/mus_westplaguec_gd01',
                    'cataclysm/mus_westplaguec_gn01',
                    'cataclysm/mus_westplaguec_gn02',
                    'cataclysm/mus_winterspring_gu01',
                    'cataclysm/mus_winterspring_gu02',
                    'cataclysm/mus_winterspring_gu03',
                    'cataclysm/mus_winterspring_gu04',
                    'cataclysm/mus_winterspring_gu05',
                    'cataclysm/mus_wordsandmusicbyevent_e01',
                }
            }
        }
    }
}
